###
# Copyright (2020) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---

kits_folder: "{{ lookup('env','HOME') }}/kits"

#
# IMPORTANT:
#   If you change the version number you also MUST change the hash (checksum)
#   for the corresponding file. The checksums specified with each element in
#   the kits_bom array are for the versions specified below. If you change
#   the version, you will have to change the hash field as well.
#
#   For a production deployment, make sure you have a hash specified for each
#   and every element in the kits_bom array below.  For testing purposes, you
#   may comment out the hash property of one of the element and experiment
#   with another vesion number.
#
#   The value / format of the version is used to form the URL which is used
#   to download the component.  There is no guarantee that the formatting of
#   this URL will stay the same in the future.
#

kits_rke_version: v1.1.3
kits_rancher_cli_version: v2.4.5
kits_kubectl_cli_version: v1.19.3
kits_helm_cli_version: v3.2.4
kits_harbor_version: v2.0.1              # only v2+ tested/supported
kits_compose_version: 1.26.0
kits_nginxplus_version: v1.7.2

#kits_rke_version: v1.2.6
#kits_rancher_cli_version: v2.4.10
#kits_kubectl_cli_version: v1.20.4
#kits_helm_cli_version: v3.5.3
#kits_harbor_version: v2.1.4              # only v2+ tested/supported
#kits_compose_version: 1.28.5
#kits_nginxplus_version: v1.10.1

#ubuntu_iso:
#  url: "http://old-releases.ubuntu.com/releases/18.04.4/ubuntu-18.04-server-amd64.iso"
#  hash: "sha256:a7f5c7b0cdd0e9560d78f1e47660e066353bb8a79eb78d1fc3f4ea62a07e6cbc"

ubuntu_iso:
  url: "https://cdimage.ubuntu.com/releases/18.04.5/release/ubuntu-18.04.5-server-amd64.iso"
  hash: "sha256:8c5fc24894394035402f66f3824beb7234b757dd2b5531379cb310cedfdf0996"

#ubuntu_iso:
#  url: "https://releases.ubuntu.com/20.04.2/ubuntu-20.04.2-live-server-amd64.iso"
#  hash: "sha256:d1f2bf834bbe9bb43faf16f9be992a6f3935e65be0edece1dee2aa6eb1767423"

#centos_iso:
#  url: "http://centos.mirror.constant.com/7.8.2003/isos/x86_64/CentOS-7-x86_64-Everything-2003.iso"
#  hash: "sha256:4120aff542c2f9a30bcf90d4d79e39511e5d9eabdf202566a94ff24ea7f0974c"

centos_iso:
  url: "http://centos.mirror.lstn.net/7.9.2009/isos/x86_64/CentOS-7-x86_64-Everything-2009.iso"
  hash: "sha256:689531cce9cf484378481ae762fae362791a9be078fda10e4f6977bf8fa71350"

centos8_iso:
  url: "http://mirrors.usc.edu/pub/linux/distributions/centos/8.1.1911/isos/x86_64/CentOS-8.1.1911-x86_64-dvd1.iso"
  hash: "sha256:3ee3f4ea1538e026fff763e2b284a6f20b259d91d1ad5688f5783a67d279423b"

os_iso: "{% if packer_os_flavor is defined and packer_os_flavor == 'centos' %}{{ centos_iso }}{% elif packer_os_flavor is defined and packer_os_flavor == 'centos8' %}{{ centos8_iso }}{% else %}{{ ubuntu_iso }}{% endif %}"


kits_bom:
  nginxplus:
    url: "https://github.com/nginxinc/kubernetes-ingress/archive/{{ kits_nginxplus_version }}.tar.gz"
    hash: "sha256:e0087bb32162ce0545a3a02a0e9e4d69e8339ddb563c60ab1883f52fc75b3028"        # checksum for v1.7.2
#    hash: "sha256:C7D2A152C5FC029558584B34D977CD80CD32118A086317688E63BB034E94AF70"        # checksum for v1.10.1
    target:  "{{ kits_folder }}/{{ kits_nginxplus_version }}.tar.gz"

  docker_compose:
    url: "https://github.com/docker/compose/releases/download/{{ kits_compose_version }}/docker-compose-linux-x86_64"
    hash: "sha256:ff6816932a57eab448798105926adbe4363b82f217802b105ade2edad95706cb"        # checksum for 1.26.0
#    hash: "sha256:46406eb5d8443cc0163a483fcff001d557532a7fad5981e268903ad40b75534c"        # checksum for 1.28.5
    target:  "{{ kits_folder }}/docker-compose-linux-x86_64"

  harbor:
    url: "https://github.com/goharbor/harbor/releases/download/{{ kits_harbor_version }}/harbor-online-installer-{{ kits_harbor_version }}.tgz"
    hash: "md5:a7e541d625fcf3297aabfb994c63d9a5"                                           # checksum for v2.0.1
#    hash: "md5:b9a298fe668440480faaadb7e7ae3050"                                           # checksum for v2.1.4
    target: "{{ kits_folder }}/harbor-online-installer-{{ kits_harbor_version }}.tgz"

  helmcli:
    url:  https://get.helm.sh/helm-{{ kits_helm_cli_version }}-linux-amd64.tar.gz
    hash: "sha256:8eb56cbb7d0da6b73cd8884c6607982d0be8087027b8ded01d6b2759a72e34b1"        # checksum for 3.2.4
#    hash: "sha256:2170a1a644a9e0b863f00c17b761ce33d4323da64fc74562a3a6df2abbf6cd70"        # checksum for 3.5.3
    script: |
      cd {{ kits_folder }}
      tar -xvf helm-{{ kits_helm_cli_version }}-linux-amd64.tar.gz linux-amd64/helm
      mv ./linux-amd64/helm .

  kubectlcli:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kits_kubectl_cli_version }}/bin/linux/amd64/kubectl
    hash: "sha256:84eeb8237448e4f431fef0f0ec0ba8b07558d8e52d5a7e89b4ae64dadcffbe66"        # checksum for 1.19.3
#    hash: "sha256:98e8aea149b00f653beeb53d4bd27edda9e73b48fed156c4a0aa1dabe4b1794c"        # checksum for 1.20.4


  ranchercli:
    url:  https://github.com/rancher/cli/releases/download/{{ kits_rancher_cli_version }}/rancher-linux-amd64-{{ kits_rancher_cli_version }}.tar.gz
    hash: "sha256:ed03829bdbb8c3102af0820c662efdeafafbf431e7e24948702b1f34f1f0ae6f"        # checksum for v2.4.5
#    hash: "sha256:81887743affea241c5d8ca768742260ff09f762ceaf41a728048522498e433a3"        # checksum for v2.4.10
    script: |
      cd {{ kits_folder }}
      tar -xvf rancher-linux-amd64-{{ kits_rancher_cli_version }}.tar.gz  ./rancher-{{ kits_rancher_cli_version }}/rancher
      mv  ./rancher-{{ kits_rancher_cli_version }}/rancher . 

  rkecli:
    url: https://github.com/rancher/rke/releases/download/{{ kits_rke_version }}/rke_linux-amd64
    hash: "sha256:fcbffe476afc21ca27b86f6b29d4009338436846b79abe41d6e075e1b788186a"        # checksum for v1.1.3
#    hash: "sha256:6d4a44931cf2fddbac742b24a4172ecf41ab199eee047cb8fa598e15e45fff8c"        # checksum for v1.2.6
    script: |
      cd {{ kits_folder }}
      mv ./rke_linux-amd64 ./rke

  packer:
    url: https://releases.hashicorp.com/packer/1.7.0/packer_1.7.0_linux_amd64.zip
    hash: 'sha256:935e81c07381a964bdbaddde2d890c91d52e88b9e5375f3882840925f6a96893'
    script: |
      cd {{ kits_folder }}
      unzip -o packer_1.7.0_linux_amd64.zip

  os_iso: "{{ os_iso }}"
